---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: capacitor-helm
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/gimlet-io/charts/capacitor
  ref:
    semver: ">= 0.1.0"
