---
apiVersion: v1
kind: Secret
metadata:
  name: capacitor-next
  namespace: flux-system
type: Opaque
stringData:
  LICENSE_KEY: "contact laszlo at gimlet.io"
  SESSION_HASH_KEY: "base64:Hqn+wKasUuS8sSZ2ph2eWz/JgeNHdQGqeWIajWjQPnY="
  SESSION_BLOCK_KEY: "base64:BttpYa78/ms60dDNWRtvOzEUk2GBZfnMQW8bK03z98I="
  registry.yaml: |
    clusters:
    - id: in-cluster
      name: In-cluster
      apiServerURL: https://kubernetes.default.svc
      certificateAuthorityFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      serviceAccount:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
