apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - gateway-api
# - agentgateway
- namespace.yaml
- agentgateway-pod.yaml
- kagent/repository.yaml
- kagent/helm-kagent-crds.yaml
- kagent/helm-kagent.yaml
# - kagent/helm-release.yaml