apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kagent-crds
  namespace: agents
spec:
  interval: 5m
  url: oci://ghcr.io/kagent-dev/kagent/helm/kagent-crds
  ref:
    tag: "0.7.23"