apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-inspector
  namespace: kagent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-inspector-binding
subjects:
- kind: ServiceAccount
  name: k8s-inspector
  namespace: kagent
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
# apiVersion: kagent.dev/v1alpha1
# kind: MCPServer
# metadata:
#   name: k8s-inspector
#   namespace: kagent
# spec:
#   transportType: stdio
#   deployment:
#     image: node:20-slim
#     cmd: "npx -y @modelcontextprotocol/server-kubernetes"
#     port: 3000
#     serviceAccountName: k8s-inspector
---
apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: sre-assistant
  namespace: kagent
spec:
  type: Declarative
  description: >
    Specialized AI assistant for Kubernetes reliability and troubleshooting.
  declarative:
    systemMessage: "You are an expert SRE assistant specializing in Kubernetes and FluxCD. Use your tools to inspect the cluster and provide diagnostics."
    modelConfig: default-model-config
    tools:
    - mcpServer:
        apiGroup: kagent.dev
        # kind: RemoteMCPServer
        name: kagent-tool-server
        name: k8s-inspector
        namespace: kagent
        toolNames:
        - k8s_get_resources
        - k8s_get_pod_logs
        - k8s_get_events
        - k8s_describe_resource
        - prometheus_query_tool
        - prometheus_targets_tool
        - shell
      type: McpServer
